/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectButton: typeof import('./src/components/CollectButton.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    CourseFilter: typeof import('./src/components/course/CourseFilter.vue')['default']
    CourseReviewForm: typeof import('./src/components/course/CourseReviewForm.vue')['default']
    CourseReviewItem: typeof import('./src/components/course/CourseReviewItem.vue')['default']
    CreatePostForm: typeof import('./src/components/post/CreatePostForm.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    IdentifyCode: typeof import('./src/components/login/IdentifyCode.vue')['default']
    LikeButton: typeof import('./src/components/LikeButton.vue')['default']
    LoginPage: typeof import('./src/components/login/LoginPage.vue')['default']
    PostItem: typeof import('./src/components/post/PostItem.vue')['default']
    PostList: typeof import('./src/components/post/PostList.vue')['default']
    RegisterPage: typeof import('./src/components/login/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
